# -*- coding: utf-8 -*-
cols = ['numberOfDaysActuallyPlayed_totalNumOfAttempts_1', 'doReturnOnLowerLevels_averageNumOfTurnsPerCompletedLevel_1',
        'fractionOfUsefullBoosters_numberOfBoostersUsed_1', 'numberOfDaysActuallyPlayed_doReturnOnLowerLevels_1',
        'numberOfBoostersUsed_doReturnOnLowerLevels_1', 'numberOfBoostersUsed_totalScore_1',
        'totalNumOfAttempts_totalBonusScore_1', 'numberOfAttemptedLevels',
        'maxPlayerLevel_averageNumOfTurnsPerCompletedLevel_1', 'numberOfDaysActuallyPlayed',
        'doReturnOnLowerLevels_totalStarsCount_1', 'totalBonusScore_numberOfDaysActuallyPlayed_1',
        'attemptsOnTheHighestLevel_numberOfBoostersUsed_1', 'totalBonusScore_averageNumOfTurnsPerCompletedLevel_1',
        'maxPlayerLevel_numberOfAttemptedLevels_1', 'numberOfAttemptedLevels_averageNumOfTurnsPerCompletedLevel_1',
        'attemptsOnTheHighestLevel_numberOfAttemptedLevels_1', 'maxPlayerLevel_totalNumOfAttempts_1',
        'fractionOfUsefullBoosters', 'attemptsOnTheHighestLevel_totalScore_1',
        'doReturnOnLowerLevels_fractionOfUsefullBoosters_1', 'attemptsOnTheHighestLevel_maxPlayerLevel_1',
        'totalStarsCount_fractionOfUsefullBoosters_1', 'fractionOfUsefullBoosters_totalScore_1',
        'totalStarsCount_totalBonusScore_1', 'averageNumOfTurnsPerCompletedLevel_totalScore_1',
        'numberOfBoostersUsed_averageNumOfTurnsPerCompletedLevel_1',
        'averageNumOfTurnsPerCompletedLevel_totalNumOfAttempts_1', 'totalScore_totalBonusScore_1',
        'doReturnOnLowerLevels_totalNumOfAttempts_1', 'doReturnOnLowerLevels_maxPlayerLevel_1',
        'numberOfBoostersUsed_totalStarsCount_1', 'totalNumOfAttempts_attemptsOnTheHighestLevel_1',
        'numberOfAttemptedLevels_doReturnOnLowerLevels_1', 'attemptsOnTheHighestLevel_doReturnOnLowerLevels_1',
        'attemptsOnTheHighestLevel_totalBonusScore_1', 'numberOfBoostersUsed_totalBonusScore_1',
        'attemptsOnTheHighestLevel', 'fractionOfUsefullBoosters_averageNumOfTurnsPerCompletedLevel_1',
        'totalStarsCount_totalNumOfAttempts_1', 'maxPlayerLevel_totalBonusScore_1', 'doReturnOnLowerLevels',
        'averageNumOfTurnsPerCompletedLevel', 'numberOfBoostersUsed_numberOfAttemptedLevels_1',
        'numberOfAttemptedLevels_numberOfDaysActuallyPlayed_1', 'maxPlayerLevel_totalStarsCount_1',
        'fractionOfUsefullBoosters_numberOfAttemptedLevels_1', 'numberOfDaysActuallyPlayed_numberOfBoostersUsed_1',
        'numberOfBoostersUsed_maxPlayerLevel_1', 'fractionOfUsefullBoosters_numberOfDaysActuallyPlayed_1',
        'fractionOfUsefullBoosters_maxPlayerLevel_1', 'totalStarsCount',
        'averageNumOfTurnsPerCompletedLevel_numberOfDaysActuallyPlayed_1',
        'attemptsOnTheHighestLevel_averageNumOfTurnsPerCompletedLevel_1',
        'numberOfDaysActuallyPlayed_totalStarsCount_1', 'attemptsOnTheHighestLevel_fractionOfUsefullBoosters_1',
        'totalNumOfAttempts', 'numberOfBoostersUsed_totalNumOfAttempts_1',
        'maxPlayerLevel_numberOfDaysActuallyPlayed_1', 'attemptsOnTheHighestLevel_numberOfDaysActuallyPlayed_1',
        'maxPlayerLevel', 'numberOfBoostersUsed', 'totalNumOfAttempts_numberOfAttemptedLevels_1',
        'attemptsOnTheHighestLevel_totalStarsCount_1', 'averageNumOfTurnsPerCompletedLevel_totalStarsCount_1',
        'totalStarsCount_numberOfAttemptedLevels_1', 'fractionOfUsefullBoosters_totalNumOfAttempts_1',
        'totalBonusScore_fractionOfUsefullBoosters_1',
        'averageNumOfTurnsPerCompletedLevel_numberOfDaysActuallyPlayed_33',
        'totalNumOfAttempts_numberOfBoostersUsed_33']

cols_k2 = ['totalBonusScore', 'attemptsOnTheHighestLevel', 'averageNumOfTurnsPerCompletedLevel', 'totalNumOfAttempts',
           'numberOfAttemptedLevels', 'numberOfDaysActuallyPlayed', 'maxPlayerLevel', 'numberOfBoostersUsed',
           'doReturnOnLowerLevels', 'totalStarsCount', 'totalScore', 'fractionOfUsefullBoosters', 'totalBonusScore_log',
           'attemptsOnTheHighestLevel_log', 'averageNumOfTurnsPerCompletedLevel_log', 'totalNumOfAttempts_log',
           'numberOfAttemptedLevels_log', 'numberOfDaysActuallyPlayed_log', 'maxPlayerLevel_log',
           'numberOfBoostersUsed_log', 'doReturnOnLowerLevels_log', 'totalStarsCount_log', 'totalScore_log',
           'fractionOfUsefullBoosters_log']

reg_cols = ['numberOfDaysActuallyPlayed_numberOfBoostersUsed_4', 'fractionOfUsefullBoosters_numberOfAttemptedLevels_3',
            'numberOfAttemptedLevels_averageNumOfTurnsPerCompletedLevel_33',
            'numberOfBoostersUsed_numberOfDaysActuallyPlayed_4',
            'averageNumOfTurnsPerCompletedLevel_totalBonusScore_44', 'fractionOfUsefullBoosters_maxPlayerLevel_11',
            'totalScore_numberOfBoostersUsed_3', 'totalNumOfAttempts_numberOfDaysActuallyPlayed_3',
            'attemptsOnTheHighestLevel_maxPlayerLevel_33', 'numberOfAttemptedLevels_attemptsOnTheHighestLevel_44',
            'numberOfBoostersUsed_numberOfAttemptedLevels_3', 'totalStarsCount_totalNumOfAttempts_44',
            'fractionOfUsefullBoosters_totalStarsCount_3', 'attemptsOnTheHighestLevel_fractionOfUsefullBoosters_4',
            'numberOfAttemptedLevels_numberOfDaysActuallyPlayed_44', 'totalScore_fractionOfUsefullBoosters_33',
            'fractionOfUsefullBoosters_averageNumOfTurnsPerCompletedLevel_44',
            'totalNumOfAttempts_numberOfDaysActuallyPlayed_33', 'totalBonusScore_totalNumOfAttempts_3',
            'fractionOfUsefullBoosters_numberOfDaysActuallyPlayed_11', 'doReturnOnLowerLevels_totalStarsCount_33',
            'maxPlayerLevel_totalStarsCount_4', 'maxPlayerLevel_totalStarsCount_1',
            'fractionOfUsefullBoosters_totalStarsCount_44', 'totalNumOfAttempts_totalNumOfAttempts_3',
            'fractionOfUsefullBoosters_numberOfDaysActuallyPlayed_22', 'maxPlayerLevel_totalBonusScore_3',
            'totalStarsCount_totalScore_3', 'totalScore_attemptsOnTheHighestLevel_3',
            'fractionOfUsefullBoosters_maxPlayerLevel_4', 'numberOfDaysActuallyPlayed_attemptsOnTheHighestLevel_4',
            'totalScore_numberOfAttemptedLevels_3', 'numberOfDaysActuallyPlayed_fractionOfUsefullBoosters_4',
            'totalScore_fractionOfUsefullBoosters_3', 'totalBonusScore_attemptsOnTheHighestLevel_44',
            'doReturnOnLowerLevels_maxPlayerLevel_3', 'totalBonusScore_numberOfDaysActuallyPlayed_4',
            'numberOfBoostersUsed_totalNumOfAttempts_3', 'attemptsOnTheHighestLevel_totalStarsCount_44',
            'averageNumOfTurnsPerCompletedLevel_attemptsOnTheHighestLevel_33',
            'numberOfBoostersUsed_attemptsOnTheHighestLevel_4', 'attemptsOnTheHighestLevel_totalStarsCount_4',
            'attemptsOnTheHighestLevel_totalNumOfAttempts_4', 'numberOfAttemptedLevels_numberOfDaysActuallyPlayed_3',
            'attemptsOnTheHighestLevel_totalScore_44', 'numberOfAttemptedLevels_numberOfDaysActuallyPlayed_4',
            'fractionOfUsefullBoosters_numberOfDaysActuallyPlayed_4',
            'fractionOfUsefullBoosters_averageNumOfTurnsPerCompletedLevel_3',
            'fractionOfUsefullBoosters_averageNumOfTurnsPerCompletedLevel_4',
            'numberOfDaysActuallyPlayed_attemptsOnTheHighestLevel_44', 'maxPlayerLevel_numberOfDaysActuallyPlayed_4',
            'fractionOfUsefullBoosters_totalNumOfAttempts_33', 'doReturnOnLowerLevels_totalNumOfAttempts_22',
            'totalNumOfAttempts_averageNumOfTurnsPerCompletedLevel_4',
            'attemptsOnTheHighestLevel_doReturnOnLowerLevels_33',
            'attemptsOnTheHighestLevel_attemptsOnTheHighestLevel_3',
            'averageNumOfTurnsPerCompletedLevel_fractionOfUsefullBoosters_44',
            'maxPlayerLevel_numberOfAttemptedLevels_1',
            'attemptsOnTheHighestLevel_averageNumOfTurnsPerCompletedLevel_4',
            'maxPlayerLevel_numberOfAttemptedLevels_3', 'attemptsOnTheHighestLevel_numberOfDaysActuallyPlayed_4',
            'maxPlayerLevel_numberOfDaysActuallyPlayed_33', 'maxPlayerLevel_fractionOfUsefullBoosters_44',
            'numberOfAttemptedLevels_totalScore_3', 'numberOfDaysActuallyPlayed_totalStarsCount_3',
            'fractionOfUsefullBoosters_attemptsOnTheHighestLevel_4', 'totalBonusScore_numberOfAttemptedLevels_3',
            'totalBonusScore_numberOfAttemptedLevels_4', 'numberOfDaysActuallyPlayed_totalScore_4',
            'totalNumOfAttempts_totalStarsCount_4', 'attemptsOnTheHighestLevel_numberOfDaysActuallyPlayed_3',
            'averageNumOfTurnsPerCompletedLevel_numberOfBoostersUsed_3', 'numberOfDaysActuallyPlayed_maxPlayerLevel_44',
            'totalBonusScore_maxPlayerLevel_3', 'numberOfAttemptedLevels_totalBonusScore_4',
            'fractionOfUsefullBoosters_totalStarsCount_11',
            'fractionOfUsefullBoosters_averageNumOfTurnsPerCompletedLevel_33',
            'averageNumOfTurnsPerCompletedLevel_attemptsOnTheHighestLevel_4',
            'numberOfAttemptedLevels_numberOfDaysActuallyPlayed_33', 'maxPlayerLevel_fractionOfUsefullBoosters_3',
            'numberOfDaysActuallyPlayed_numberOfAttemptedLevels_4',
            'averageNumOfTurnsPerCompletedLevel_attemptsOnTheHighestLevel_3',
            'averageNumOfTurnsPerCompletedLevel_numberOfBoostersUsed_33', 'fractionOfUsefullBoosters_totalBonusScore_3',
            'totalNumOfAttempts_numberOfDaysActuallyPlayed_4', 'doReturnOnLowerLevels_totalNumOfAttempts_44',
            'totalScore_totalNumOfAttempts_3', 'attemptsOnTheHighestLevel_numberOfBoostersUsed_3',
            'numberOfBoostersUsed_doReturnOnLowerLevels_3', 'numberOfDaysActuallyPlayed_maxPlayerLevel_4',
            'attemptsOnTheHighestLevel_numberOfBoostersUsed_4',
            'averageNumOfTurnsPerCompletedLevel_totalNumOfAttempts_44', 'maxPlayerLevel_numberOfDaysActuallyPlayed_3',
            'numberOfAttemptedLevels_maxPlayerLevel_1', 'totalNumOfAttempts_fractionOfUsefullBoosters_33',
            'totalBonusScore_totalBonusScore_4', 'totalBonusScore_totalBonusScore_3',
            'numberOfAttemptedLevels_totalScore_33', 'maxPlayerLevel_totalNumOfAttempts_44',
            'fractionOfUsefullBoosters_numberOfBoostersUsed_11', 'fractionOfUsefullBoosters_totalNumOfAttempts_11',
            'maxPlayerLevel_fractionOfUsefullBoosters_4', 'numberOfDaysActuallyPlayed_totalBonusScore_4',
            'doReturnOnLowerLevels_maxPlayerLevel_22', 'totalBonusScore_numberOfDaysActuallyPlayed_44',
            'totalScore_totalNumOfAttempts_33', 'doReturnOnLowerLevels_numberOfDaysActuallyPlayed_11',
            'doReturnOnLowerLevels_numberOfAttemptedLevels_22', 'doReturnOnLowerLevels_totalStarsCount_44',
            'numberOfDaysActuallyPlayed_totalNumOfAttempts_4', 'numberOfDaysActuallyPlayed_totalNumOfAttempts_3',
            'numberOfDaysActuallyPlayed_numberOfBoostersUsed_44', 'numberOfBoostersUsed_maxPlayerLevel_3',
            'attemptsOnTheHighestLevel_doReturnOnLowerLevels_3', 'numberOfBoostersUsed_maxPlayerLevel_1',
            'numberOfAttemptedLevels_averageNumOfTurnsPerCompletedLevel_3',
            'fractionOfUsefullBoosters_totalBonusScore_11', 'attemptsOnTheHighestLevel_attemptsOnTheHighestLevel_33',
            'fractionOfUsefullBoosters_totalStarsCount_33', 'totalStarsCount_attemptsOnTheHighestLevel_4',
            'numberOfDaysActuallyPlayed_totalStarsCount_33', 'numberOfAttemptedLevels_fractionOfUsefullBoosters_33',
            'totalNumOfAttempts_attemptsOnTheHighestLevel_4', 'numberOfAttemptedLevels_maxPlayerLevel_33',
            'attemptsOnTheHighestLevel_maxPlayerLevel_3', 'numberOfBoostersUsed_numberOfBoostersUsed_4',
            'attemptsOnTheHighestLevel_fractionOfUsefullBoosters_44', 'totalStarsCount_numberOfAttemptedLevels_3',
            'totalNumOfAttempts_maxPlayerLevel_33', 'maxPlayerLevel_numberOfAttemptedLevels_33',
            'maxPlayerLevel_numberOfBoostersUsed_1', 'totalNumOfAttempts_fractionOfUsefullBoosters_44',
            'averageNumOfTurnsPerCompletedLevel_fractionOfUsefullBoosters_4',
            'numberOfDaysActuallyPlayed_numberOfDaysActuallyPlayed_4', 'totalScore_attemptsOnTheHighestLevel_44',
            'totalStarsCount_fractionOfUsefullBoosters_44', 'doReturnOnLowerLevels_totalStarsCount_3',
            'doReturnOnLowerLevels_numberOfAttemptedLevels_44', 'fractionOfUsefullBoosters_numberOfAttemptedLevels_11',
            'maxPlayerLevel_attemptsOnTheHighestLevel_44', 'totalScore_numberOfDaysActuallyPlayed_33',
            'doReturnOnLowerLevels_totalScore_33', 'totalStarsCount_maxPlayerLevel_1',
            'fractionOfUsefullBoosters_totalNumOfAttempts_3', 'fractionOfUsefullBoosters_numberOfDaysActuallyPlayed_33',
            'totalStarsCount_maxPlayerLevel_4', 'doReturnOnLowerLevels_totalStarsCount_22',
            'numberOfBoostersUsed_fractionOfUsefullBoosters_44', 'numberOfAttemptedLevels_totalNumOfAttempts_3',
            'numberOfAttemptedLevels_fractionOfUsefullBoosters_3', 'maxPlayerLevel_totalBonusScore_33',
            'fractionOfUsefullBoosters_totalBonusScore_33', 'attemptsOnTheHighestLevel_numberOfBoostersUsed_33',
            'totalScore_numberOfDaysActuallyPlayed_4', 'totalScore_numberOfDaysActuallyPlayed_3',
            'averageNumOfTurnsPerCompletedLevel_totalNumOfAttempts_4',
            'numberOfBoostersUsed_numberOfDaysActuallyPlayed_44', 'totalStarsCount_totalNumOfAttempts_4',
            'totalNumOfAttempts_fractionOfUsefullBoosters_3', 'fractionOfUsefullBoosters_maxPlayerLevel_44',
            'doReturnOnLowerLevels_totalScore_3']

xgb2_cols = [
    'averageNumOfTurnsPerCompletedLevel_numberOfDaysActuallyPlayed_2',
    'averageNumOfTurnsPerCompletedLevel_numberOfDaysActuallyPlayed_4',
    'numberOfDaysActuallyPlayed_attemptsOnTheHighestLevel_11',
    'maxPlayerLevel_averageNumOfTurnsPerCompletedLevel_11',
    'numberOfDaysActuallyPlayed_numberOfBoostersUsed_11',
    'numberOfBoostersUsed_maxPlayerLevel_1',
    'maxPlayerLevel_totalBonusScore_3',
    'totalNumOfAttempts_numberOfAttemptedLevels_11',
    'numberOfDaysActuallyPlayed_totalScore_22',
    'attemptsOnTheHighestLevel_totalNumOfAttempts_4',
    'totalBonusScore_numberOfBoostersUsed_4',
    'maxPlayerLevel_numberOfBoostersUsed_3',
    'averageNumOfTurnsPerCompletedLevel_numberOfBoostersUsed_1',
    'numberOfDaysActuallyPlayed_maxPlayerLevel_4',
    'totalScore_totalNumOfAttempts_33',
    'averageNumOfTurnsPerCompletedLevel_totalNumOfAttempts_33',
    'maxPlayerLevel_averageNumOfTurnsPerCompletedLevel_44',
    'totalNumOfAttempts_numberOfBoostersUsed_1',
    'totalNumOfAttempts_attemptsOnTheHighestLevel_33',
    'numberOfDaysActuallyPlayed_totalNumOfAttempts_44',
    'doReturnOnLowerLevels_totalScore_22',
    'numberOfDaysActuallyPlayed_averageNumOfTurnsPerCompletedLevel_11',
    'totalNumOfAttempts_attemptsOnTheHighestLevel_1',
    'maxPlayerLevel_doReturnOnLowerLevels_33'
]